<?php
function form($det=array(),$new_ref="",$today=""){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
					$CI->html->sForm("purchase_orders/db","general-form");
						$CI->html->hidden('id',iSetObj($det,'id'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$params = array('class'=>'rOkay','ro-msg'=>'Reference must not be empty');
								if(iSetObj($det,'id')){
									$params['readonly'] = 'readonly';
								}
								$CI->html->inputPaper('Reference:','reference',iSetObj($det,'reference',$new_ref),null,$params);
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Order Date:','order_date',iSetObjDate($det,'order_date',$today),null,array('class'=>'rOkay pick-date','ro-msg'=>'Order date must not be empty'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->supplierDropPaper('Supplier:','supplier_id',iSetObj($det,'supplier_id'),null,array('class'=>'rOkay','ro-msg'=>'Supplier must not be empty'));
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->locationDropPaper('Recieve Location:','rcv_loc_id',iSetObj($det,'rcv_loc_id'),null,array('class'=>'rOkay','ro-msg'=>'Receive location must not be empty'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->H(4,"",array('class'=>'page-header'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->sTable(array('class'=>'table paper-table','id'=>'details'));
									$CI->html->sTablehead();
										$CI->html->sRow();
											$CI->html->th('Material');
											$CI->html->th('Order Qty');
											$CI->html->th('Cost');
											$CI->html->th('Total Cost');
											$CI->html->th('');
										$CI->html->eRow();
									$CI->html->eTablehead();
									$CI->html->sTableBody();
										$CI->html->sRow(array('class'=>'input-row'));
											$matDrop = $CI->html->materialsDrop('','mat_id',null,null,array('class'=>'paper-select','return'=>true));
											$matName = $CI->html->hidden('mat_name','',array('return'=>true));
											$CI->html->td($matDrop." ".$matName,array('style'=>'width:30%;'));
											$ordInput = $CI->html->decimal('','ord_qty',null,null,2,array('return'=>true,'style'=>'width:100px;'));
											$CI->html->td($ordInput,array('style'=>'text-align:center'));
											$costInput = $CI->html->decimal('','cost',num(0),null,2,array('return'=>true,'style'=>'width:100px;'));
											$CI->html->td($costInput,array('style'=>'text-align:center'));
											$costTotal = $CI->html->span(num(0),array('id'=>'cost_total','return'=>true));
											$costTotalhid = $CI->html->hidden('cost_total_hid','',array('return'=>true));
											$CI->html->td($costTotal." ".$costTotalhid);
											$CI->html->td();
										$CI->html->eRow();
									$CI->html->eTableBody();
								$CI->html->eTable();
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->sDivRow();
							$CI->html->sDivCol();
								$CI->html->textarea("","memo",iSetObj($det,'memo'),"Add Remarks Here...");			
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eForm();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}
