<?php
function form($det=array(),$det_rows=array(),$new_ref="",$today=""){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
					$CI->html->sForm("receive_orders/db","general-form");
						$CI->html->hidden('order_id',iSetObj($det,'id'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$params = array('class'=>'rOkay','ro-msg'=>'Reference must not be empty');
								$CI->html->inputPaper('Reference:','reference',$new_ref,null,$params);
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Receive Date:','receive_date',$today,null,array('class'=>'rOkay pick-date','ro-msg'=>'Order date must not be empty'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();

						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Order Ref:','order_ref',iSetObj($det,'reference'),null,array('readonly'=>'readonly'));
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Order Date:','order_date',iSetObjDate($det,'order_date'),null,array('readonly'=>'readonly'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();

						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->supplierDropPaper('Supplier:','supplier_id',iSetObj($det,'supplier_id'),null,array('disabled'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->locationDropPaper('Recieve Location:','rcv_loc_id',iSetObj($det,'rcv_loc_id'),null,array('class'=>'rOkay','ro-msg'=>'Receive location must not be empty'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->H(4,"",array('class'=>'page-header'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->sTable(array('class'=>'table paper-table','id'=>'details'));
									$CI->html->sTablehead();
										$CI->html->sRow();
											$CI->html->th('Material');
											$CI->html->th('Order Qty');
											$CI->html->th('Remaining Qty');
											$CI->html->th('Receive Qty');
										$CI->html->eRow();
									$CI->html->eTablehead();
									$CI->html->sTableBody();
										foreach ($det_rows as $res) {
											$CI->html->sRow();
												$CI->html->td($res->mat_name);
												$CI->html->td($res->order_qty);
												$CI->html->td($res->order_qty - $res->rcv_qty);
												$rcvInput = $CI->html->decimal('','rcv_qtys['.$res->mat_id.']',$res->order_qty - $res->rcv_qty,null,2,array('return'=>true,'style'=>'width:100px;'));
												$remhid = $CI->html->hidden('rem_qtys['.$res->mat_id.']',$res->order_qty - $res->rcv_qty,array('return'=>true));
												$ordhid = $CI->html->hidden('ord_qtys['.$res->mat_id.']',$res->order_qty,array('return'=>true));
												$CI->html->td($rcvInput.' '.$remhid.' '.$ordhid);
											$CI->html->eRow();
										}
									$CI->html->eTableBody();
								$CI->html->eTable();
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->textarea("","order_memo",iSetObj($det,'memo'),"",array('readonly'=>'readonly'));			
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->textarea("","memo",'',"Add Remarks Here...");			
							$CI->html->eDivCol();
						$CI->html->eDivRow();
					$CI->html->eForm();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}
function rec_view($det=array(),$det_rows=array()){
	$CI =& get_instance();
	$CI->html->sDivRow();
		$CI->html->sDivCol(10,'left',1);
			$CI->html->sBox('solid');
				$CI->html->sBoxBody(array('class'=>'paper'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Reference:','reference',iSetObj($det,'reference'),null,array('readonly'=>'readonly'));
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Receive Date:','receive_date',iSetObjDate($det,'receive_date'),null,array('readonly'=>'readonly'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();

						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Order Ref:','order_ref',iSetObj($det,'order_ref'),null,array('readonly'=>'readonly'));
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->inputPaper('Order Date:','order_date',iSetObjDate($det,'order_date'),null,array('readonly'=>'readonly'));
							$CI->html->eDivCol();
						$CI->html->eDivRow();

						$CI->html->sDivRow();
							$CI->html->sDivCol(6);
								$CI->html->supplierDropPaper('Supplier:','supplier_id',iSetObj($det,'supplier_id'),null,array('disabled'=>''));
							$CI->html->eDivCol();
							$CI->html->sDivCol(6);
								$CI->html->locationDropPaper('Recieve Location:','loc_id',iSetObj($det,'loc_id'),null,array('disabled'=>''));
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->H(4,"",array('class'=>'page-header'));
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->sTable(array('class'=>'table paper-table','id'=>'details'));
									$CI->html->sTablehead();
										$CI->html->sRow();
											$CI->html->th('Material');
											$CI->html->th('Order Qty');
											$CI->html->th('Remaining Qty');
											$CI->html->th('Receive Qty');
										$CI->html->eRow();
									$CI->html->eTablehead();
									$CI->html->sTableBody();
										foreach ($det_rows as $res) {
											$CI->html->sRow();
												$CI->html->td($res->mat_name);
												$CI->html->td($res->order_qty);
												$CI->html->td($res->remain_qty);
												$CI->html->td($res->rcv_qty);
											$CI->html->eRow();
										}
									$CI->html->eTableBody();
								$CI->html->eTable();
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->textarea("","order_memo",iSetObj($det,'order_memo'),"",array('readonly'=>'readonly'));			
							$CI->html->eDivCol();
						$CI->html->eDivRow();
						$CI->html->sDivRow();
							$CI->html->sDivCol(12);
								$CI->html->textarea("","memo",iSetObj($det,'memo'),"",array('readonly'=>'readonly'));			
							$CI->html->eDivCol();
						$CI->html->eDivRow();
				$CI->html->eBoxBody();
			$CI->html->eBox();
		$CI->html->eDivCol();
	$CI->html->eDivRow();
	return $CI->html->code();
}
